[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.2",
    "gunicorn[eventlet]>=23.0.0",
    "uvicorn[standard]>=0.36.0",
    "aiosqlite>=0.20.0",
]
